### ISSUE TITLE
Initial `ACCESS-RAM3` deployment configuration

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/ACCESS-RAM3#1]
Create the initial `spack.yaml`/`config/versions.json` updates to deploy `ACCESS-RAM3`. 

## TODO

 - [x] Create Github Environment and `secrets`/`vars`. See https://github.com/ACCESS-NRI/ACCESS-RAM3/settings/secrets/actions
 - [x] Update `config/versions.json`
 - [x] Get a working `spack.yaml` deployed onto `Prerelease`
 - [ ] Update README.md
